/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_natives_FFmpegNative */

#ifndef _Included_com_test_natives_FFmpegNative
#define _Included_com_test_natives_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_natives_FFmpegNative
 * Method:    avcodec_find_decoder
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_test_natives_FFmpegNative_avcodec_1find_1decoder
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_test_natives_FFmpegNative
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_test_natives_FFmpegNative_getVersion
  (JNIEnv *, jobject);



JNIEXPORT jint JNICALL Java_com_test_natives_FFmpegNative_aacInit
  (JNIEnv *, jobject);

/*
 * Class:     com_test_natives_FFmpegNative
 * Method:    EncodingH264
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_test_natives_FFmpegNative_EncodingH264
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_test_natives_FFmpegNative
 * Method:    CloseVideo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_natives_FFmpegNative_CloseVideo
  (JNIEnv *, jobject);

/*
 * Class:     com_test_natives_FFmpegNative
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_natives_FFmpegNative_avcodecinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_test_natives_FFmpegNative
 * Method:    EncodingAAC
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_test_natives_FFmpegNative_EncodingAAC
  (JNIEnv *, jobject, jbyteArray,jint);

/*
 * Class:     com_test_natives_FFmpegNative
 * Method:    CloseAudio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_natives_FFmpegNative_CloseAudio
  (JNIEnv *, jobject);

/*
 * Class:     com_test_natives_FFmpegNative
 * Method:    Composite264Aac
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_test_natives_FFmpegNative_Composite264Aac
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);


JNIEXPORT jboolean JNICALL Java_com_test_natives_FFmpegNative_cmdOrder
  (JNIEnv *, jobject, jobjectArray);


JNIEXPORT jint JNICALL Java_com_test_natives_FFmpegNative_init
  (JNIEnv *, jclass , jstring , jint , jint ) ;


JNIEXPORT jint JNICALL Java_com_test_natives_FFmpegNative_push
  (JNIEnv *, jclass , jbyteArray , jint , jint ) ;


JNIEXPORT jint JNICALL Java_com_test_natives_FFmpegNative_stop
  (JNIEnv *, jclass ) ;

#ifdef __cplusplus
}
#endif
#endif
