/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <assert.h>
#include <sys/ptrace.h>
#include <dlfcn.h>
/* Header for class com_test_natives_FFmpegNative */

#ifndef _Included_com_lgyw_emergency_natives_AntiDebugNative
#define _Included_com_lgyw_emergency_natives_AntiDebugNative
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_lgyw_emergency_natives_AntiDebugNative_checkProgramStatue
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_lgyw_emergency_natives_AntiDebugNative_uninstall
  (JNIEnv *, jobject,jstring );


#ifdef __cplusplus
}
#endif
#endif
